sokusekiya/sokuseki

- .circleci/config.yml
- README.md
ちょいと寄り道して CI を設定しちゃう。Rails のテストはあとからやっていくとして、まずはライトに Rubocop だけを動かす。微妙に Rails のテストを動かすための、未来のための設定が混じっているけれどあまり気にせずにいこう。
> CircleCI で Rubocop を動かす

- config/application.rb
- docker-compose.yml
本格的に時刻データを扱うようになってオッとなる瞬間が出てきたのでやっちゃうよ〜！ :calendar: :clock3: :earth_asia:
> タイムゾーンを日本に合わせる

- app/controllers/activities/on_month_controller.rb
- app/controllers/application_controller.rb
- app/controllers/welcome_controller.rb
- app/models/activity.rb
- app/models/authentication.rb
- app/views/activities/github/_event.html.slim
- app/views/activities/on_month/index.html.slim
- app/views/layouts/_navigator.html.slim
- app/views/layouts/application.html.slim
- app/views/welcome/_for_user.html.slim
- app/views/welcome/_for_visitor.html.slim
- app/views/welcome/index.html.slim
- config/routes.rb
データを貯めておけるようになったので、それを画面に表示するぞ〜！
そのまま列挙するとけっこうな数になってしまうので「月ごと」「種類ごと」に数を表示したり絞り込んだりできるようにしようと思っている。
あと、いわゆるトップページとなる場所は、
- ログインしていたら、その人の Activity をいい感じに表示する
- ログインしていなかったら、ログイン用の導線のみを表示する
という分岐を入れたいので、実装しながらどういう処理にするか考える。
> 最初のバージョンとして最小限の表示をつくっていく

- app/views/welcome/index.html.slim
いろいろと整理している間に「サインインしていたら」の判定が抜けていたので直す。
> サインインしている場合の処理なので判定を入れる

- config/environments/production.rb
今となってはこうしておく方が自然で、その方がトラブルも少ないはず〜 :ok_hand:
> production 環境では常に https にする

- app/models/authentication.rb
さまざまな要因でたまに通信は失敗するので、そこで処理が止まってしまわないように rescue する :muscle:
> GitHub との通信でエラーが発生するケースを rescue する

- config/environments/production.rb
> production でのログ出力を抑える

- app/views/activities/github/_event.html.slim
> リポジトリ作成イベント用の表示を用意する

- app/views/activities/github/_event.html.slim
```
リポジトリ org/repo のコミット abc123 にコメントした
```
という形で！
> コミットへのコメント用の表示を用意する

- app/helpers/activities_helper.rb
そもそも重複したデータが発生するような Activity のデータの持ち方がよくないのかもしれないけれど、uniq するデメリットもないのでシュッとやってしまおう :dash:
> 同じ内容の行があっても仕方ないので uniq する

- README.md
開発するぞーという気持ちになった時に迷わないようにします 📝
> 開発のはじめかたを追加する

- .circleci/config.yml
- Dockerfile
- Gemfile
- Gemfile.lock
> Ruby 2.6.1

- docker-compose.yml
> tmp/pids/server.pid が残っていてサーバーが起動できない問題を解決する

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/activities/on_month/index.html.slim
- app/views/layouts/application.html.slim
[チャートを表示したい · Issue #13 · june29/sokuseki](https://github.com/june29/sokuseki/issues/13) の対応 💪 
チャートには、[Chart.js | Open source HTML5 Charts for your website](https://www.chartjs.org/)を使ってみます。
- チャートの見た目が良さそう
- ドキュメントが充実してる
- Star数が多いので人気がありそう
参考になりそうなリンク
- [色の組み合わせ方を身につけよう: 棒グラフや円グラフなど、データをビジュアル化した際に効果的な配色 | コリス](https://coliss.com/articles/build-websites/operation/design/right-color-palettes-for-data-visualizations.html)
- [The color system - Material Design](https://material.io/design/color/#tools-for-picking-colors)
> アクティビティをチャート表示する

- CHANGELOG.md
作る時に参考にしてたページへのリンクになってたので、Sokusekiのリンクに直します 😓
> Change Logのリンク修正

- app/controllers/welcome_controller.rb
- app/models/activity.rb
- app/views/welcome/_annual_report.slim
- app/views/welcome/_yearly_report.slim
- app/views/welcome/index.html.slim
サインインしている時、トップページに1年間のアクティビティ推移のグラフを表示するようにします。
> トップページに1年間のアクティビティ推移を表示できるようにする

- app/controllers/welcome_controller.rb
- app/models/activity.rb
- app/views/welcome/_annual_report.slim
- sprintf が Rubocop に怒られていたのでそこを変えようと思って着手した
- 処理を見たら整理できそう〜となったので `@annual_activities` の組み立て方を変えた
- ついでにガード節を入れてネストを浅くした
- データが 3 ヶ月前の分までしかなかったら、チャートも 3 ヶ月前までしか表示されなくなった
- それでいいと思っているのでそうした
> WelcomeController の処理を整理する

- app/assets/stylesheets/application.css.erb
この人間のアイコンが出ていなかったので出すようにしたいです。
<table><tr><th>修正前</th><th>修正後</th></tr><tr><td>
</td><td><img width="287" alt="スクリーンショット 2019-06-28 7 26 20" src="https://user-images.githubusercontent.com/726349/60305008-1f30e700-9976-11e9-8d20-810b994a8c2b.png">
</td></tr></table>
> サインインのアイコン画像が出ていなかったので出したい

- app/controllers/welcome_controller.rb
- app/views/welcome/_annual_report.slim
現在表示されているline chartは線がぐんにょりしていて遷移がわかりにくいので、各月のレポートにあるような積み上げのbar chartを表示できるようにします。
> annual reportをbarで表示する

- README.md
https://circleci.com/gh/june29/sokuseki
https://circleci.com/gh/sokusekiya/sokuseki
> Update CircleCI URL

- app/controllers/welcome_controller.rb
- app/models/activity.rb
- app/views/welcome/_annual_report.slim
Rubocopが怒ってきている箇所がいくつかあるので修正します。
また、 #114 でApprove後に指摘のあった箇所も一緒に直しています。
> Rubocopから怒られている箇所を修正

- README.md
ローカルの環境を作り直してみた際に、READMEの手順だとサーバーが立ち上がらなかったので修正しました。
(いずれはsetup scriptを作って、それを実行してください！って言えた方がいいなあと思いつつ、ひとまずREADMEを修正します。)
> bundle installしないとサーバーが立ち上がらないので、手順に追加

- .circleci/config.yml
- Dockerfile
- Gemfile
- Gemfile.lock
コミッターのみなさんに感謝しながら Ruby 2.7.0 を使わせてもらいましょう :gem:
> Ruby 2.7.0

- .circleci/config.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
> Ruby 3.0.0

- .github/workflows/ci.yml
> GitHub Actions の CI の設定ファイルをシュッとさせる

- .github/workflows/review.yml
https://github.com/marketplace/actions/run-brakeman-with-reviewdog のドキュメントに従って設定してみます。
> reviewdog/action-brakeman を設定する

- .github/workflows/review.yml
メンテしていこうと思ったので、まずはCI通るようにしたいす。
> CIが落ちてるのを治す

- .dockerignore
- .github/workflows/docker.yml
- Dockerfile.release
- Gemfile.lock
- Makefile
- app/controllers/sessions_controller.rb
- app/models/authentication.rb
- app/models/user.rb
- config/application.rb
- config/environments/production.rb
- config/initializers/octokit.rb
- config/initializers/omniauth.rb
- spec/models/activity_spec.rb
- spec/models/shared_link_spec.rb
- spec/rails_helper.rb
- spec/requests/sessions_spec.rb
heroku以外で動かせるようにDockerイメージをビルドします。
> プロダクション環境で利用できるDockerイメージを追加する

- app/models/user.rb
> cache expired records

- Gemfile.lock
Reverts sokusekiya/sokuseki#558
> Revert "Bump octokit from 6.0.1 to 6.1.0"

- Gemfile.lock
Reverts sokusekiya/sokuseki#557
> Revert "Bump rack from 2.2.6.2 to 2.2.6.3"

- app/controllers/sessions_controller.rb
Reverts sokusekiya/sokuseki#550
> Revert "access tokenが失効するケースがあっため、ログインしたら更新する"

- app/models/shared_link.rb
> shared linkの有効期間を指定可能にする
